# Generated by Django 5.2.1 on 2025-08-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='reason',
            field=models.CharField(choices=[('late', '遲交'), ('absence', '缺席'), ('no_uniform', '未穿制服')], default='late', max_length=50),
        ),
    ]
