# Generated by Django 5.2.1 on 2025-08-13 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsync', '0003_alter_violation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
