# Generated by Django 5.2.1 on 2025-09-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsync', '0004_alter_violation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
    ]
