# Generated by Django 5.2.1 on 2025-10-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsync', '0005_event_delete_violation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='identity',
            field=models.CharField(choices=[('hedgehog', '🦔'), ('dino', '🦕'), ('both', '兩個人')], default='both', max_length=10),
        ),
    ]
