# Generated by Django 5.2.1 on 2025-10-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsync', '0006_remove_event_description_event_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='identity',
            field=models.CharField(choices=[('h', '🦔'), ('t', '🦕'), ('both', '兩個人')], default='t', max_length=10),
        ),
    ]
